// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Servo
{
    internal static unsafe partial class ServoNative
    {
        const string __DllName = "servo_ffi";





        [DllImport(__DllName, EntryPoint = "servo_last_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* servo_last_error();

        [DllImport(__DllName, EntryPoint = "servo_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_free_string(byte* ptr);

        [DllImport(__DllName, EntryPoint = "servo_free_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_free_bytes(byte* ptr, nuint len);

        [DllImport(__DllName, EntryPoint = "servo_protocol_registry_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* servo_protocol_registry_new();

        [DllImport(__DllName, EntryPoint = "servo_protocol_registry_register", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte servo_protocol_registry_register(void* registry, byte* scheme, CProtocolHandler handler);

        [DllImport(__DllName, EntryPoint = "servo_protocol_registry_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_protocol_registry_destroy(void* registry);

        [DllImport(__DllName, EntryPoint = "servo_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* servo_new(CEventLoopWaker waker, byte* resource_path, void* protocol_registry);

        [DllImport(__DllName, EntryPoint = "servo_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_destroy(void* handle);

        [DllImport(__DllName, EntryPoint = "servo_spin_event_loop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_spin_event_loop(void* handle);

        [DllImport(__DllName, EntryPoint = "servo_set_delegate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_set_delegate(void* handle, ServoCallbacks callbacks);

        [DllImport(__DllName, EntryPoint = "servo_set_preference", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_set_preference(void* handle, byte* name, byte* value);

        [DllImport(__DllName, EntryPoint = "rendering_context_new_software", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* rendering_context_new_software(uint width, uint height);

        [DllImport(__DllName, EntryPoint = "rendering_context_new_hardware", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* rendering_context_new_hardware(uint width, uint height);

        [DllImport(__DllName, EntryPoint = "rendering_context_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rendering_context_destroy(void* handle);

        [DllImport(__DllName, EntryPoint = "rendering_context_frame_export_kind", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint rendering_context_frame_export_kind(void* handle);

        [DllImport(__DllName, EntryPoint = "rendering_context_acquire_frame", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte rendering_context_acquire_frame(void* handle, ServoFrameInfo* out_info);

        [DllImport(__DllName, EntryPoint = "timeline_semaphore_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* timeline_semaphore_new();

        [DllImport(__DllName, EntryPoint = "timeline_semaphore_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void timeline_semaphore_destroy(void* handle);

        [DllImport(__DllName, EntryPoint = "timeline_semaphore_signal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void timeline_semaphore_signal(void* handle, ulong value);

        [DllImport(__DllName, EntryPoint = "timeline_semaphore_signaled_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong timeline_semaphore_signaled_value(void* handle);

        [DllImport(__DllName, EntryPoint = "rendering_context_signal_after_gpu_work", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rendering_context_signal_after_gpu_work(void* handle, void* semaphore, ulong value);

        [DllImport(__DllName, EntryPoint = "rendering_context_release_frame", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rendering_context_release_frame(void* handle, ulong frame_id);

        [DllImport(__DllName, EntryPoint = "rendering_context_resize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rendering_context_resize(void* handle, uint width, uint height);

        [DllImport(__DllName, EntryPoint = "rendering_context_present", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rendering_context_present(void* handle);

        [DllImport(__DllName, EntryPoint = "rendering_context_make_current", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte rendering_context_make_current(void* handle);

        [DllImport(__DllName, EntryPoint = "rendering_context_read_pixels", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* rendering_context_read_pixels(void* handle, uint* out_width, uint* out_height, nuint* out_len);

        [DllImport(__DllName, EntryPoint = "rendering_context_read_pixels_into", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte rendering_context_read_pixels_into(void* handle, byte* dest, nuint dest_len, uint* out_width, uint* out_height);

        [DllImport(__DllName, EntryPoint = "webview_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* webview_new(void* servo_handle, void* rendering_ctx_handle, WebViewCallbacks callbacks, ClipboardCallbacks clipboard, byte* initial_url);

        [DllImport(__DllName, EntryPoint = "create_new_webview_build", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* create_new_webview_build(nuint request_handle, void* rendering_ctx_handle, WebViewCallbacks callbacks, ClipboardCallbacks clipboard);

        [DllImport(__DllName, EntryPoint = "create_new_webview_dismiss", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void create_new_webview_dismiss(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "authentication_request_authenticate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void authentication_request_authenticate(nuint request_handle, byte* username, byte* password);

        [DllImport(__DllName, EntryPoint = "authentication_request_dismiss", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void authentication_request_dismiss(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "web_resource_load_dismiss", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void web_resource_load_dismiss(nuint handle);

        [DllImport(__DllName, EntryPoint = "web_resource_load_intercept", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void web_resource_load_intercept(nuint handle, ushort status_code, byte* body, nuint body_len);

        [DllImport(__DllName, EntryPoint = "web_resource_load_cancel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void web_resource_load_cancel(nuint handle);

        [DllImport(__DllName, EntryPoint = "webview_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_destroy(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_load_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_load_url(void* handle, byte* url);

        [DllImport(__DllName, EntryPoint = "webview_reload", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_reload(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_go_back", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_go_back(void* handle, nuint steps);

        [DllImport(__DllName, EntryPoint = "webview_go_forward", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_go_forward(void* handle, nuint steps);

        [DllImport(__DllName, EntryPoint = "webview_paint", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_paint(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_resize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_resize(void* handle, uint width, uint height);

        [DllImport(__DllName, EntryPoint = "webview_focus", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_focus(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_blur", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_blur(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_show", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_show(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_hide", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_hide(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_set_hidpi_scale", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_set_hidpi_scale(void* handle, float scale);

        [DllImport(__DllName, EntryPoint = "webview_get_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* webview_get_url(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_get_title", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* webview_get_title(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_get_load_status", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte webview_get_load_status(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_get_cursor", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte webview_get_cursor(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_is_focused", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte webview_is_focused(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_is_animating", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte webview_is_animating(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_can_go_back", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte webview_can_go_back(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_can_go_forward", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte webview_can_go_forward(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_send_mouse_button", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong webview_send_mouse_button(void* handle, byte action, ushort button, float x, float y);

        [DllImport(__DllName, EntryPoint = "webview_send_mouse_move", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong webview_send_mouse_move(void* handle, float x, float y);

        [DllImport(__DllName, EntryPoint = "webview_send_mouse_left_viewport", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong webview_send_mouse_left_viewport(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_send_key_event", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong webview_send_key_event(void* handle, byte state, uint key_char, byte* key_code, uint modifiers);

        [DllImport(__DllName, EntryPoint = "webview_send_wheel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong webview_send_wheel(void* handle, double delta_x, double delta_y, double delta_z, byte mode, float x, float y);

        [DllImport(__DllName, EntryPoint = "webview_send_scroll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_send_scroll(void* handle, float delta_x, float delta_y, float point_x, float point_y);

        [DllImport(__DllName, EntryPoint = "webview_send_touch", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong webview_send_touch(void* handle, byte event_type, int touch_id, float x, float y);

        [DllImport(__DllName, EntryPoint = "webview_send_editing_action", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong webview_send_editing_action(void* handle, byte action);

        [DllImport(__DllName, EntryPoint = "webview_set_page_zoom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_set_page_zoom(void* handle, float zoom);

        [DllImport(__DllName, EntryPoint = "webview_get_page_zoom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern float webview_get_page_zoom(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_exit_fullscreen", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_exit_fullscreen(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_set_throttled", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_set_throttled(void* handle, byte throttled);

        [DllImport(__DllName, EntryPoint = "webview_evaluate_javascript", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_evaluate_javascript(void* handle, byte* script, delegate* unmanaged[Cdecl]<void*, byte*, byte*, void> callback, void* callback_data);

        [DllImport(__DllName, EntryPoint = "dialog_alert_dismiss", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void dialog_alert_dismiss(nuint dialog_handle);

        [DllImport(__DllName, EntryPoint = "dialog_confirm_respond", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void dialog_confirm_respond(nuint dialog_handle, byte confirmed);

        [DllImport(__DllName, EntryPoint = "dialog_prompt_respond", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void dialog_prompt_respond(nuint dialog_handle, byte* value);

        [DllImport(__DllName, EntryPoint = "navigation_request_allow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void navigation_request_allow(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "navigation_request_deny", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void navigation_request_deny(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "permission_request_allow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void permission_request_allow(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "permission_request_deny", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void permission_request_deny(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "allow_or_deny_request_allow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void allow_or_deny_request_allow(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "allow_or_deny_request_deny", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void allow_or_deny_request_deny(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "bluetooth_device_pick", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void bluetooth_device_pick(nuint request_handle, nuint device_index);

        [DllImport(__DllName, EntryPoint = "bluetooth_device_cancel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void bluetooth_device_cancel(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "unload_request_allow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void unload_request_allow(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "unload_request_deny", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void unload_request_deny(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "select_element_respond", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void select_element_respond(nuint request_handle, long selected_id);

        [DllImport(__DllName, EntryPoint = "context_menu_select", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void context_menu_select(nuint request_handle, byte action);

        [DllImport(__DllName, EntryPoint = "context_menu_dismiss", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void context_menu_dismiss(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "webview_take_screenshot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_take_screenshot(void* handle, delegate* unmanaged[Cdecl]<void*, byte*, uint, uint, nuint, void> callback, void* callback_data);

        [DllImport(__DllName, EntryPoint = "webview_get_favicon", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* webview_get_favicon(void* handle, uint* out_width, uint* out_height, byte* out_format, nuint* out_len);

        [DllImport(__DllName, EntryPoint = "user_content_manager_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* user_content_manager_new(void* servo_handle);

        [DllImport(__DllName, EntryPoint = "user_content_manager_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void user_content_manager_destroy(void* handle);

        [DllImport(__DllName, EntryPoint = "user_script_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* user_script_new(byte* script, byte* source_file);

        [DllImport(__DllName, EntryPoint = "user_script_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void user_script_destroy(void* handle);

        [DllImport(__DllName, EntryPoint = "user_stylesheet_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* user_stylesheet_new(byte* source, byte* url);

        [DllImport(__DllName, EntryPoint = "user_stylesheet_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void user_stylesheet_destroy(void* handle);

        [DllImport(__DllName, EntryPoint = "user_content_manager_add_script", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void user_content_manager_add_script(void* ucm_handle, void* script_handle);

        [DllImport(__DllName, EntryPoint = "user_content_manager_remove_script", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void user_content_manager_remove_script(void* ucm_handle, void* script_handle);

        [DllImport(__DllName, EntryPoint = "user_content_manager_add_stylesheet", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void user_content_manager_add_stylesheet(void* ucm_handle, void* stylesheet_handle);

        [DllImport(__DllName, EntryPoint = "user_content_manager_remove_stylesheet", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void user_content_manager_remove_stylesheet(void* ucm_handle, void* stylesheet_handle);

        [DllImport(__DllName, EntryPoint = "servo_site_data", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* servo_site_data(void* handle, byte storage_types);

        [DllImport(__DllName, EntryPoint = "servo_clear_site_data", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_clear_site_data(void* handle, byte** sites, nuint sites_len, byte storage_types);

        [DllImport(__DllName, EntryPoint = "servo_clear_cookies", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_clear_cookies(void* handle, delegate* unmanaged[Cdecl]<void*, void> callback, void* user_data);

        [DllImport(__DllName, EntryPoint = "servo_clear_session_cookies", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_clear_session_cookies(void* handle, delegate* unmanaged[Cdecl]<void*, void> callback, void* user_data);

        [DllImport(__DllName, EntryPoint = "servo_set_cookie_for_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int servo_set_cookie_for_url(void* handle, byte* url, byte* cookie, delegate* unmanaged[Cdecl]<void*, void> callback, void* user_data);

        [DllImport(__DllName, EntryPoint = "servo_cookies_for_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* servo_cookies_for_url(void* handle, byte* url, byte source);

        [DllImport(__DllName, EntryPoint = "servo_cookies_for_url_async", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int servo_cookies_for_url_async(void* handle, byte* url, byte source, delegate* unmanaged[Cdecl]<void*, byte*, void> callback, void* user_data);

        [DllImport(__DllName, EntryPoint = "servo_cache_entries", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* servo_cache_entries(void* handle);

        [DllImport(__DllName, EntryPoint = "servo_clear_cache", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_clear_cache(void* handle);

        [DllImport(__DllName, EntryPoint = "file_picker_select_and_submit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void file_picker_select_and_submit(nuint handle, byte** paths, nuint paths_len);

        [DllImport(__DllName, EntryPoint = "file_picker_dismiss", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void file_picker_dismiss(nuint handle);

        [DllImport(__DllName, EntryPoint = "color_picker_select_and_submit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void color_picker_select_and_submit(nuint handle, byte has_color, byte r, byte g, byte b);

        [DllImport(__DllName, EntryPoint = "color_picker_dismiss", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void color_picker_dismiss(nuint handle);

        [DllImport(__DllName, EntryPoint = "webview_notify_theme_change", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_notify_theme_change(void* handle, byte theme);

        [DllImport(__DllName, EntryPoint = "webview_notify_media_session_action", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_notify_media_session_action(void* handle, byte action);

        [DllImport(__DllName, EntryPoint = "webview_adjust_pinch_zoom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_adjust_pinch_zoom(void* handle, float delta, float center_x, float center_y);

        [DllImport(__DllName, EntryPoint = "webview_get_pinch_zoom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern float webview_get_pinch_zoom(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_send_ime_composition", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_send_ime_composition(void* handle, byte state, byte* data);

        [DllImport(__DllName, EntryPoint = "webview_send_ime_dismissed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_send_ime_dismissed(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_toggle_webrender_debugging", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_toggle_webrender_debugging(void* handle, byte option);

        [DllImport(__DllName, EntryPoint = "webview_capture_webrender", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_capture_webrender(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_toggle_sampling_profiler", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_toggle_sampling_profiler(void* handle, ulong rate_ms, ulong max_duration_ms);

        [DllImport(__DllName, EntryPoint = "servo_initialize_gl_accelerated_media", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_initialize_gl_accelerated_media(byte display_type, nuint display_ptr, byte api, byte context_type, nuint context_ptr);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ServoFrameInfo
    {
        public ulong frame_id;
        public void* native_handle;
        public uint width;
        public uint height;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CEventLoopWaker
    {
        public void* user_data;
        public delegate* unmanaged[Cdecl]<void*, void> wake;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ServoCallbacks
    {
        public void* user_data;
        public delegate* unmanaged[Cdecl]<void*, byte, byte*, void> on_error;
        public delegate* unmanaged[Cdecl]<void*, ushort, byte*, void> on_devtools_started;
        public delegate* unmanaged[Cdecl]<void*, byte, byte*, void> on_console_message;
        public delegate* unmanaged[Cdecl]<void*, byte> on_request_devtools_connection;
        public delegate* unmanaged[Cdecl]<void*, byte*, byte*, byte, byte, nuint, void> on_load_web_resource;
        public delegate* unmanaged[Cdecl]<void*, byte*, byte*, void> on_show_notification;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct WebViewCallbacks
    {
        public void* user_data;
        public delegate* unmanaged[Cdecl]<void*, void> on_new_frame_ready;
        public delegate* unmanaged[Cdecl]<void*, byte, void> on_load_status_changed;
        public delegate* unmanaged[Cdecl]<void*, byte*, void> on_url_changed;
        public delegate* unmanaged[Cdecl]<void*, byte*, void> on_title_changed;
        public delegate* unmanaged[Cdecl]<void*, byte, void> on_cursor_changed;
        public delegate* unmanaged[Cdecl]<void*, byte, void> on_focus_changed;
        public delegate* unmanaged[Cdecl]<void*, byte, void> on_animating_changed;
        public delegate* unmanaged[Cdecl]<void*, void> on_favicon_changed;
        public delegate* unmanaged[Cdecl]<void*, ulong, byte, void> on_input_event_handled;
        public delegate* unmanaged[Cdecl]<void*, byte*, nuint, nuint, void> on_history_changed;
        public delegate* unmanaged[Cdecl]<void*, void> on_closed;
        public delegate* unmanaged[Cdecl]<void*, byte, void> on_fullscreen_changed;
        public delegate* unmanaged[Cdecl]<void*, byte*, byte*, void> on_crashed;
        public delegate* unmanaged[Cdecl]<void*, byte, byte*, void> on_console_message;
        public delegate* unmanaged[Cdecl]<void*, byte*, nuint, void> on_show_alert;
        public delegate* unmanaged[Cdecl]<void*, byte*, nuint, void> on_show_confirm;
        public delegate* unmanaged[Cdecl]<void*, byte*, byte*, nuint, void> on_show_prompt;
        public delegate* unmanaged[Cdecl]<void*, byte*, nuint, void> on_request_navigation;
        public delegate* unmanaged[Cdecl]<void*, byte, nuint, void> on_request_permission;
        public delegate* unmanaged[Cdecl]<void*, nuint, void> on_request_unload;
        public delegate* unmanaged[Cdecl]<void*, byte, byte*, void> on_media_session_event;
        public delegate* unmanaged[Cdecl]<void*, byte*, long, int, int, int, int, nuint, void> on_show_select_element;
        public delegate* unmanaged[Cdecl]<void*, byte*, int, int, nuint, void> on_show_context_menu;
        public delegate* unmanaged[Cdecl]<void*, nuint, void> on_request_create_new_webview;
        public delegate* unmanaged[Cdecl]<void*, byte*, byte, nuint, void> on_request_authentication;
        public delegate* unmanaged[Cdecl]<void*, void> on_hide_embedder_control;
        public delegate* unmanaged[Cdecl]<void*, byte*, byte*, byte, byte, nuint, void> on_load_web_resource;
        public delegate* unmanaged[Cdecl]<void*, byte*, void> on_status_text_changed;
        public delegate* unmanaged[Cdecl]<void*, void> on_traversal_complete;
        public delegate* unmanaged[Cdecl]<void*, int, int, void> on_request_move_to;
        public delegate* unmanaged[Cdecl]<void*, int, int, void> on_request_resize_to;
        public delegate* unmanaged[Cdecl]<void*, byte*, byte*, byte, nuint, void> on_request_protocol_handler;
        public delegate* unmanaged[Cdecl]<void*, byte*, byte*, void> on_show_notification;
        public delegate* unmanaged[Cdecl]<void*, byte*, nuint, void> on_show_bluetooth_device_dialog;
        public delegate* unmanaged[Cdecl]<void*, nuint, byte, nuint, void> on_gamepad_haptic_effect;
        public delegate* unmanaged[Cdecl]<void*, CScreenGeometry*, byte> get_screen_geometry;
        public delegate* unmanaged[Cdecl]<void*, byte*, byte, byte*, nuint, void> on_show_file_picker;
        public delegate* unmanaged[Cdecl]<void*, byte, byte, byte, byte, int, int, int, int, nuint, void> on_show_color_picker;
        public delegate* unmanaged[Cdecl]<void*, byte, byte*, long, byte, byte, int, int, int, int, void> on_show_input_method;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ClipboardCallbacks
    {
        public void* user_data;
        public delegate* unmanaged[Cdecl]<void*, byte*> get_text;
        public delegate* unmanaged[Cdecl]<void*, byte*, void> set_text;
        public delegate* unmanaged[Cdecl]<void*, void> clear;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CProtocolResponse
    {
        public byte* body;
        public nuint body_len;
        public byte* content_type;
        public ushort status_code;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CProtocolHandler
    {
        public void* user_data;
        public delegate* unmanaged[Cdecl]<byte*, void*, CProtocolResponse*, byte> load;
        public byte is_fetchable;
        public byte is_secure;
        public byte** privileged_paths;
        public nuint privileged_paths_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CScreenGeometry
    {
        public int size_width;
        public int size_height;
        public int available_width;
        public int available_height;
        public int window_x;
        public int window_y;
        public int window_width;
        public int window_height;
    }



}
